### ISSUE TITLE
Problem with the display of keys in the legend of Maps

### ISSUE THREAD

**Issue by yaminiagarwal** [tcpd/lokdhaba#24] opened 2017-03-25 08:13 UTC
Step 1 - Go to Election Data Visualization and then AE tab
Step 2 - Choose any state (Delhi,Maharashtra, Mizoram)
Step 3 - Choose Visualization type "Winning Margin of Party Winners: Map" or "Constituency Type Party Winners"
Issue- The legend is not uniform, i.e., the keys are displayed haphazardly.
![image](https://cloud.githubusercontent.com/assets/26666904/24320728/df8b894c-1160-11e7-940c-41bb1e0bc96e.png)

**Comment by chinuhub** [comment] 2017-03-27 18:53
Closing this issue as I am not able to reproduce it.

**Closed as completed by chinuhub** 2017-03-27 18:53 UTC
Labels: P2, Visualization

**Comment by hangal** [comment] 2017-03-27 18:54
btw, generally only the person opening the issue is supposed to close it.

@Rajkamalsingh23 fyi.

**Comment by yaminiagarwal** [comment] 2017-04-01 13:13
The problem still persists.
![image](https://cloud.githubusercontent.com/assets/26666904/24579034/0a41f9c8-170b-11e7-9d67-8f16dac5e61b.png)

**Comment by chinuhub** [comment] 2017-04-02 09:25
![git issue](https://cloud.githubusercontent.com/assets/9635185/24585957/53877014-17b4-11e7-902a-0cebf800fdee.png)
The legends are displaying properly to me. @yaminiagarwal  Can you please check again?
